---
language: python
python: "2.7"

sudo: required
dist: trusty

addons:
  apt:
    packages:
      - python-pip

install:
  # Install yamllint
  - pip install yamllint

script:
  # Check YAML validity
  - yamllint -c yamllint.yml .
