---

#
# sets up the host that runs ansible.nodejs.org
#

- hosts: infra-softlayer-ubuntu1804-x64-2
  gather_facts: yes
  roles:
    - bootstrap
    - package-upgrade
    - ansible-tower

  pre_tasks:
    - name: check if secrets are properly set
      fail:
      failed_when: not {{ secret }}
      loop_control:
        loop_var: secret
      with_items:
        - awx_password
        - awx_org
