---

#
# add PPA for gcc updates
#

- name: "repo : add Ubuntu Toolchain PPA"
  apt_repository:
    repo: 'ppa:ubuntu-toolchain-r/test'
    state: present
    update_cache: true
  register: has_updated_package_repo
